CREATE NODE TABLE Person(id INT64, name INT32, age INT64, PRIMARY KEY (id))
CREATE NODE TABLE City(id INT64, name INT32, population INT64, PRIMARY KEY (id))
CREATE REL TABLE LivesIn(FROM Person TO City)
